### ISSUE TITLE
GitHub action ?

### ISSUE THREAD

**Issue by pinkforest** [Lioness100/rspell#19]
### Is there an existing issue or pull request for this?

- [X] I have searched the existing issues and pull requests

### Feature description

Would there be a GitHub action so this can be added into CI ?

### Desired solution

GitHub action that uses cache to pull the required dependencies so it can be used in CI

Could maybe potentially perhaps use this in rustsec/advisory-db among other places

**Comment by Lioness100** [comment]
Hi! You can use https://github.com/streetsidesoftware/cspell-action. Not developed by me, but developed by the person who made cspell, which is what rspell uses.

**Comment by Lioness100** [comment]
Also, regarding your "cargo-rspell" question, you can find a precompiled binary of rspell attached to the most recent release, which doesn't require node or npn for usage.

**Comment by pinkforest** [comment]
Oh okay, thanks for the great work :)
